---
sections:
  - label: Blog Posts
    name: posts
    path: tina-cloud-blog-content/posts
    templates:
      - article
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Authors
    name: authors
    path: tina-cloud-blog-content/authors
    templates:
      - author
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
